const PARAM_IS_NULL = -1001
const USER_IS_EXISTS = -1002
const USER_NOT_EXISTS = -1003
const PWD_IS_ERROR = -1004
const TOKEN_ERROR = -1005

const DATABASE_OPERATE_ERROR = -2001
const NOT_UPDATE_PERMISSION = -4001
module.exports = {
  PARAM_IS_NULL,
  USER_IS_EXISTS,
  USER_NOT_EXISTS,
  PWD_IS_ERROR,
  TOKEN_ERROR,
  DATABASE_OPERATE_ERROR,
  NOT_UPDATE_PERMISSION
}
